---
- name: Install Docker
  hosts: all
  become: true
  tasks:

    - name: Install packege
      apt:
        name:
          - ca-certificates
          - curl
          - openssh-server
          - tzdata
          - perl
          - postfix
        update-cache: true

    - name: Get pre-installed script
      get_url:
        src: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh
        dest: /tmp/script.deb.sh
        mode: 0755

    - name: Preinstall script
      command:
        cmd: /tmp/script.deb.sh

    - name: Install Gitlab
      apt:
        name:
          - gitlab-ee
        update-cache: true
