image: docker:20.10.16

stages:
  - test
  - build
  - review
  - stage
  - production

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:20.10.16-dind

test_unit_job_1:
  stage: test
  image: python:3.6
  script:
    - cd crawler/search_engine_crawler
    - pip3 install -r requirements.txt -r requirements-test.txt
    - echo "Тестирование кода...search_engine_crawler"
    - python3 -m unittest discover -s tests/
    - coverage run -m unittest discover -s tests/
    - coverage report --include crawler/crawler.py > report_test_search_engine_crawler.txt
    - cp -f report_test_search_engine_crawler.txt ${CI_PROJECT_DIR}

test_unit_job_2:
  stage: test
  image: python:3.6
  script:
    - cd crawler/search_engine_ui
    - pip install -r requirements.txt -r requirements-test.txt
    - echo "Тестирование кода...search_engine_ui"
    - python -m unittest discover -s tests/
    - coverage run -m unittest discover -s tests/
    - coverage report --include ui/ui.py > report_test_search_engine_ui.txt
    - cp -f report_test_search_engine_ui.txt ${CI_PROJECT_DIR}


build_crawler:
  stage: build
  before_script:
    - cd crawler/search_engine_crawler
  script:
    - docker build -t crawler:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA .
    - docker run --name crawler-$CI_COMMIT_SHORT_SHA -d crawler:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  environment:
    name: branch/$CI_COMMIT_REF_NAME
  only:
    - branches
  except:
    - master

build_crawler_ui:
  stage: build
  before_script:
    - cd crawler/search_engine_ui
  script:
    - docker build -t crawler_ui:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA .
    - docker run --name crawler_ui-$CI_COMMIT_SHORT_SHA -d -p 8000:8000 crawler_ui:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  environment:
    name: branch/$CI_COMMIT_REF_NAME
  only:
    - branches
  except:
    - master

deploy_dev_job_1:
  stage: review
  before_script:
    - cd crawler/search_engine_crawler
  script:
    - docker login --username iam --password t1.9euelZrMic_InZiPyMaMxpzHmo6Qke3rnpWams6bnZ2XksmSlpSUy8bNio7l8_d9O2Fo-e9nEEIR_t3z9z1qXmj572cQQhH-zef1656VmpGex42KzseYkZPGypOXjImQ7_0.Yf_h2sDfqOoFooXMxoOUtMdCFQ1iQZ73mbN7D4puMBibmDTYFwtIDvdnsb9B0NMde3XygTa0UGXcumcQcbIPAw cr.yandex
    - docker build -t cr.yandex/crp1b5c9anstbgfjiuvg/crawler:crawler
    - docker push cr.yandex/crp1b5c9anstbgfjiuvg/crawler:crawler
  environment:
    name: branch/$CI_COMMIT_REF_NAME
  only:
    - branches
  except:
    - master

deploy_dev_job_2:
  stage: review
  before_script:
    - cd crawler/search_engine_ui
  script:
    - docker login --username iam --password t1.9euelZrMic_InZiPyMaMxpzHmo6Qke3rnpWams6bnZ2XksmSlpSUy8bNio7l8_d9O2Fo-e9nEEIR_t3z9z1qXmj572cQQhH-zef1656VmpGex42KzseYkZPGypOXjImQ7_0.Yf_h2sDfqOoFooXMxoOUtMdCFQ1iQZ73mbN7D4puMBibmDTYFwtIDvdnsb9B0NMde3XygTa0UGXcumcQcbIPAw cr.yandex
    - docker build -t cr.yandex/crp1b5c9anstbgfjiuvg/crawler_ui:crawler_ui
    - docker push cr.yandex/crp1b5c9anstbgfjiuvg/crawler_ui:crawler_ui
  environment:
    name: branch/$CI_COMMIT_REF_NAME
  only:
    - branches
  except:
    - master


branch_review:
  stage: review
  script:
    - echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
 stage: production
 when: manual
 only:
   - /^\d+\.\d+\.\d+/
 script:
   - echo 'Deploy'
 environment:
   name: production
   url: https://example.com
