---
- name: Touche docker compose
  hosts: all
  vars_files:
    - variable.yml
  tasks:

  - name: Make docker compose file for gitlab
    template:
      src: templates/docker-compose-gitlab.yml.j2
      dest: /srv/gitlab/docker-compose.yml

  - name: Docker Compose UP
    community.docker.docker_compose:
      project_src: /srv/gitlab
