---
- name: Touche docker compose
  hosts: all
  become: true
  tasks:

  - name: Make docker compose file for gitlab
    template:
      src: templates/docker-compose-gitlab.yml.j2
      dest: /srv/gitlab/docker-compose.yml

  - name: Docker Compose DOWN
    community.docker.docker_compose:
      project_src: /srv/gitlab/
      state: absent


  - name: Docker Compose UP
    community.docker.docker_compose:
      project_src: /srv/gitlab
