---
- name: Install Docker
  hosts: all
  become: true
  tasks:

    - name: Install packege
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
        update-cache: true

    - name: Add docker key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg
        state: present

    - name: Install stable apt_repository
      apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
          https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        update-cache: true
        filename: docker

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        update-cache: true

    - name: Install Docker Module for Python
      pip:
        name:
          - docker
          - docker-compose

    - name: Add user in group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
        
    - name: Create directory for gitlab
      file:
        path: /srv/gitlab/{{ item }}
        state: directory
        owner: "{{ ansible_user }}"
      loop:
         - config
         - data
         - logs

    - name: Create directory for crawler
      file:
        path: /opt/crawler
        state: directory
        owner: "{{ ansible_user }}"
