---
- name: Register runner
  hosts: all
  become: true

  vars:
    - YOUR_VM_IP: "51.250.88.45"
    - YOUR_TOKEN: "GR1348941iJe6s_zWJ_uRxU_MU76E"
    - YA_REGISTRY: "crpj11uvphqt5o72mocm"

  tasks:

  - name: Make shell script
    ansible.builtin.template:
      src: templates/register_runner.sh.j2
      dest: /srv/gitlab/register_runner.sh
      owner: "{{ ansible_user }}"
      mode: 0774

  - name: Register runner
    command:
      cmd: /srv/gitlab/register_runner.sh
