---
- name: Register runner
  hosts: all
  become: true
  tasks:

  - name: Make shell script
    ansible.builtin.template:
      src: templates/register_runner.sh.j2
      dest: /srv/gitlab/register_runner.sh
      owner: "{{ ansible_user }}"
      mode: 0774

  - name: Register runner
    command:
      cmd: /srv/gitlab/register_runner.sh
