---
- name: Register runner
  hosts: all
  become: true

  vars:
    - YOUR_VM_IP: "51.250.95.235"
    - YOUR_TOKEN: "GR13489419b-UFfCe-T_WYKkayock"
    - YA_REGISTRY: "crpf1i27ln09cg0p3bg3"

  tasks:

  - name: Make shell script
    ansible.builtin.template:
      src: templates/register_runner.sh.j2
      dest: /srv/gitlab/register_runner.sh
      owner: "{{ ansible_user }}"
      mode: 0774

  - name: Register runner
    command:
      cmd: /srv/gitlab/register_runner.sh
