---
- name: Register runner
  hosts: all
  become: true

  vars:
    - YOUR_VM_IP: "62.84.125.100"
    - YOUR_TOKEN: "GR1348941Cw1zZ1gaBo5-5hsshowo"
    - YA_REGISTRY: "crp9o1sme0bui1fk3inu"

  tasks:

  - name: Make shell script
    ansible.builtin.template:
      src: templates/register_runner.sh.j2
      dest: /srv/gitlab/register_runner.sh
      owner: "{{ ansible_user }}"
      mode: 0774

  - name: Register runner
    command:
      cmd: /srv/gitlab/register_runner.sh
